# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\4th_year\HIS\Project\repo\PyQt5-DICOM-Viewer\DICOMmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1241, 698)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Main.setFont(font)
        Main.setStyleSheet("/* Application Background */\n"
"QWidget {\n"
"    background-color: #282828; /* Dark Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"}\n"
"\n"
"/* Main Window */\n"
"QMainWindow {\n"
"    background-color: #282828; /* Dark Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Menu Items */\n"
"QMenu {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"}\n"
"\n"
"/* Menu Item Hover */\n"
"QMenu::item:selected {\n"
"    background-color: #444444; /* Dark Gray on hover */\n"
"}\n"
"\n"
"/* Toolbars */\n"
"QToolBar {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #0074D9; /* Dark Blue */\n"
"    color: #FFFFFF; /* White text */\n"
"    border: 2px solid #0056B3; /* Darker Blue border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 8px 16px; /* Padding around text */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"}\n"
"\n"
"/* Push Button Hover */\n"
"QPushButton:hover {\n"
"    background-color: #0056B3; /* Darker Blue on hover */\n"
"}\n"
"\n"
"/* Push Button Pressed */\n"
"QPushButton:pressed {\n"
"    background-color: #003E7D; /* Even darker blue when pressed */\n"
"}\n"
"\n"
"/* Push Button Disabled */\n"
"QPushButton:disabled {\n"
"    background-color: #DDDDDD; /* Light gray for disabled */\n"
"    color: #999999; /* Dimmed text */\n"
"    border: 2px solid #CCCCCC; /* Slightly darker border for disabled */\n"
"}\n"
"\n"
"/* LineEdits, TextEdits */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    border: 2px solid #444444; /* Dark Gray border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding around text */\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"/* LineEdit and TextEdit Focus */\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border-color: #77A1D3; /* Light Blue border when focused */\n"
"}\n"
"\n"
"/* ScrollBars */\n"
"QScrollBar:vertical {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    width: 10px; /* Scroll bar width */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #444444; /* Dark Gray scroll bar handle */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"/* Labels */\n"
"/* QLabel with Background Color */\n"
"QLabel#coloredLabel {\n"
"    background-color: #FF5733; /* Orange background */\n"
"    color: #FFFFFF; /* White text */\n"
"    padding: 5px; /* Padding around text */\n"
"    border-radius: 4px; /* Rounded corners */\n"
"}\n"
"\n"
"/* QLabel with Border */\n"
"QLabel#borderedLabel {\n"
"    border: 2px solid #3498DB; /* Border with a blue color */\n"
"    padding: 5px; /* Padding around text */\n"
"    border-radius: 4px; /* Rounded corners */\n"
"}\n"
"\n"
"/* QLabel with Custom Font */\n"
"QLabel#customFontLabel {\n"
"    font-family: \"Georgia\"; /* Custom font family */\n"
"    font-weight: bold; /* Bold text */\n"
"}\n"
"\n"
"QLabel{\n"
"    font-family: \"Georgia\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* QLabel with Text Shadow */\n"
"QLabel#shadowLabel {\n"
"    text-shadow: 2px 2px 4px #333333; /* Text shadow with offset and color */\n"
"}\n"
"\n"
"/* QLabel with Underline */\n"
"QLabel#underlinedLabel {\n"
"    text-decoration: underline; /* Underline text */\n"
"}\n"
"\n"
"/* QLabel with Strike Through */\n"
"QLabel#strikeThroughLabel {\n"
"    text-decoration: line-through; /* Strike through text */\n"
"}\n"
"\n"
"/* QLabel with Text Alignment */\n"
"QLabel#centeredLabel {\n"
"    text-align: center; /* Center-align text */\n"
"}\n"
"\n"
"/* QLabel with Text Color Gradient */\n"
"QLabel#gradientLabel {\n"
"    background: linear-gradient(to right, #3498DB, #FF5733); /* Text color gradient */\n"
"    -webkit-background-clip: text; /* Apply gradient to text */\n"
"    color: transparent; /* Hide text color */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* Slider Stylesheet */\n"
"QSlider {\n"
"    background: transparent; /* Transparent background */\n"
"    border: none; /* No border */\n"
"}\n"
"\n"
"/* Slider Groove (Track) */\n"
"QSlider::groove:horizontal {\n"
"    background: #555555; /* Gray track background */\n"
"    height: 6px; /* Height of the track */\n"
"    border-radius: 3px; /* Rounded corners */\n"
"}\n"
"\n"
"/* Slider Handle */\n"
"QSlider::handle:horizontal {\n"
"    background: #3498DB; /* Blue handle background */\n"
"    width: 16px; /* Width of the handle */\n"
"    margin: -8px 0; /* Center the handle vertically */\n"
"    border-radius: 8px; /* Round handle corners */\n"
"}\n"
"\n"
"/* Slider Handle Hovered State */\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #2581C0; /* Darker blue on hover */\n"
"}\n"
"\n"
"/* Slider Handle Pressed State */\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #1B6CAB; /* Even darker blue when pressed */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* Checkbox Stylesheet for Dark Background (Enhanced) */\n"
"QCheckBox {\n"
"    background: transparent; /* Transparent background */\n"
"    spacing: 5px; /* Spacing between the checkbox and text */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"    color: #FFFFFF; /* White text for contrast */\n"
"}\n"
"\n"
"/* Checkbox Indicator (Unchecked) */\n"
"QCheckBox::indicator {\n"
"    width: 16px; /* Width of the indicator */\n"
"    height: 16px; /* Height of the indicator */\n"
"    border: 2px solid #FFFFFF; /* White border for contrast */\n"
"    border-radius: 3px; /* Rounded indicator */\n"
"}\n"
"\n"
"/* Checkbox Indicator (Checked) */\n"
"QCheckBox::indicator:checked {\n"
"    background: #3498DB; /* Blue background when checked */\n"
"    border: 2px solid #FFFFFF; /* White border when checked */\n"
"}\n"
"\n"
"/* Checkbox Indicator (Hovered) */\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #FFFFFF; /* White border on hover for contrast */\n"
"}\n"
"\n"
"/* Checkbox Text (Unchecked) */\n"
"QCheckBox::indicator:unchecked {\n"
"    background: transparent; /* Transparent background for unchecked */\n"
"    border-radius: 3px; /* Rounded indicator */\n"
"}\n"
"\n"
"/* Checkbox Text (Checked) */\n"
"QCheckBox::indicator:checked:hover {\n"
"    border: 2px solid #FFFFFF; /* White border on hover when checked */\n"
"}\n"
"\n"
"/* Checkbox Text (Hovered) */\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 2px solid #FFFFFF; /* White border on hover for unchecked */\n"
"}\n"
"\n"
"/* Checkbox Text (Disabled) */\n"
"QCheckBox:disabled {\n"
"    color: #888888; /* Dimmed text for disabled */\n"
"}\n"
"\n"
"/* Checkbox Indicator (Disabled) */\n"
"QCheckBox::indicator:unchecked:disabled {\n"
"    background: transparent; /* Transparent background for unchecked when disabled */\n"
"    border: 2px solid #777777; /* Slightly darker gray border for unchecked when disabled */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled {\n"
"    background: #999999; /* Light gray background when checked and disabled */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* QGraphicsView Stylesheet */\n"
"QGraphicsView {\n"
"    background-color: #333333; /* Dark background color */\n"
"    border: 1px solid #555555; /* Border for the QGraphicsView */\n"
"    border-radius: 4px; /* Rounded corners */\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:horizontal, QScrollBar:vertical {\n"
"    background-color: #555555; /* Scroll bar background color */\n"
"    border-radius: 4px; /* Rounded corners for the scroll bars */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background-color: #888888; /* Scroll bar handle color */\n"
"    border-radius: 4px; /* Rounded handle */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background-color: #AAAAAA; /* Hover effect on the handle */\n"
"}\n"
"\n"
"QScrollBar::sub-line, QScrollBar::add-line {\n"
"    background: none; /* No background for arrow buttons */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px; /* Hide vertical scroll bar\'s bottom arrow button */\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px; /* Hide vertical scroll bar\'s top arrow button */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px; /* Hide horizontal scroll bar\'s right arrow button */\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px; /* Hide horizontal scroll bar\'s left arrow button */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* QTextEdit Stylesheet (Improved) */\n"
"QTextEdit {\n"
"    background-color: #282828; /* Dark background */\n"
"    border: 1px solid #444444; /* Dark gray border */\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    font-size: 4px; /* Font size */\n"
"    color: #FFFFFF; /* White text color */\n"
"    padding: 5px; /* Padding around the text */\n"
"}\n"
"\n"
"/* QTextEdit Focus State */\n"
"QTextEdit:focus {\n"
"    border-color: #3498DB; /* Blue border when focused */\n"
"}\n"
"\n"
"/* QTextEdit Scroll Bars */\n"
"QTextEdit QScrollBar:vertical {\n"
"    background-color: #282828; /* Dark background for vertical scrollbar */\n"
"    width: 12px; /* Scroll bar width */\n"
"    margin: 0px; /* No margin for scrollbar */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:vertical {\n"
"    background-color: #555555; /* Gray scrollbar handle */\n"
"    border-radius: 6px; /* Rounded scrollbar handle */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line:vertical,\n"
"QTextEdit QScrollBar::sub-line:vertical {\n"
"    background: none; /* No background for arrow buttons */\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-page:vertical,\n"
"QTextEdit QScrollBar::sub-page:vertical {\n"
"    background: none; /* No background for page buttons */\n"
"}\n"
"\n"
"\n"
"/* Custom Styles for Signal Viewer Components */\n"
"/* Add your custom styles for specific components here */\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* QMenuBar Stylesheet for Dark Theme */\n"
"QMenuBar {\n"
"    background-color: #333333; /* Dark background color */\n"
"    color: #FFFFFF; /* Text color */\n"
"    padding: 2px; /* Add some padding to the menu bar */\n"
"    border: 1px solid #444444; /* Dark gray border */\n"
"}\n"
"\n"
"/* QMenuBar Item Styles */\n"
"QMenuBar::item {\n"
"    background-color: transparent; /* Transparent background for items */\n"
"    padding: 6px 12px; /* Padding for items */\n"
"    border-radius: 4px; /* Rounded corners for items */\n"
"}\n"
"\n"
"/* QMenuBar Item Hover State */\n"
"QMenuBar::item:hover {\n"
"    background-color: #555555; /* Slightly darker background on hover */\n"
"}\n"
"\n"
"/* QMenuBar Item Pressed State */\n"
"QMenuBar::item:pressed {\n"
"    background-color: #1B6CAB; /* Darker blue background when pressed */\n"
"    color: #FFFFFF; /* White text color when pressed */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Arrow */\n"
"QMenuBar::item:open:menu {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    padding-right: 8px; /* Spacing for submenu arrow */\n"
"    border-top-right-radius: 4px; /* Rounded corner for the right side */\n"
"    border-bottom-right-radius: 4px; /* Rounded corner for the right side */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Styles */\n"
"QMenu {\n"
"    background-color: #333333; /* Dark background for submenu */\n"
"    border: 1px solid #444444; /* Dark gray border for submenu */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Item Styles */\n"
"QMenu::item {\n"
"    background-color: transparent; /* Transparent background for submenu items */\n"
"    padding: 6px 18px; /* Padding for submenu items */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Item Hover State */\n"
"QMenu::item:hover {\n"
"    background-color: #555555; /* Slightly darker background on hover for submenu items */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* QMenuBar Stylesheet with Enhanced Text */\n"
"QMenuBar {\n"
"    background-color: #333333; /* Dark background color */\n"
"    color: #FFFFFF; /* Text color */\n"
"    padding: 2px; /* Add some padding to the menu bar */\n"
"    border: 1px solid #444444; /* Dark gray border */\n"
"    font-size: 16px; /* Font size for menu bar items */\n"
"    font-weight: bold; /* Bold text for menu bar items */\n"
"}\n"
"\n"
"/* QMenuBar Item Styles */\n"
"QMenuBar::item {\n"
"    background-color: transparent; /* Transparent background for items */\n"
"    padding: 6px 12px; /* Padding for items */\n"
"    border-radius: 4px; /* Rounded corners for items */\n"
"}\n"
"\n"
"/* QMenuBar Item Hover State */\n"
"QMenuBar::item:hover {\n"
"    background-color: #555555; /* Slightly darker background on hover */\n"
"}\n"
"\n"
"/* QMenuBar Item Pressed State */\n"
"QMenuBar::item:pressed {\n"
"    background-color: #1B6CAB; /* Darker blue background when pressed */\n"
"    color: #FFFFFF; /* White text color when pressed */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Arrow */\n"
"QMenuBar::item:open:menu {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    padding-right: 8px; /* Spacing for submenu arrow */\n"
"    border-top-right-radius: 4px; /* Rounded corner for the right side */\n"
"    border-bottom-right-radius: 4px; /* Rounded corner for the right side */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Styles */\n"
"QMenu {\n"
"    background-color: #333333; /* Dark background for submenu */\n"
"    border: 1px solid #444444; /* Dark gray border for submenu */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Item Styles */\n"
"QMenu::item {\n"
"    background-color: transparent; /* Transparent background for submenu items */\n"
"    padding: 6px 18px; /* Padding for submenu items */\n"
"}\n"
"\n"
"/* QMenuBar Submenu Item Hover State */\n"
"QMenu::item:hover {\n"
"    background-color: #555555; /* Slightly darker background on hover for submenu items */\n"
"}\n"
"\n"
"\n"
"\n"
"/* ComboBox Stylesheet */\n"
"\n"
"QComboBox{\n"
"    font-family: \"Georgia\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    border: 2px solid #444444; /* Dark Gray border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding around text */\n"
"    min-width: 6em; /* Minimum width of the combo box */\n"
"    font: \"Georgia\";\n"
"}\n"
"\n"
"/* ComboBox Arrow */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    width: 15px; /* Adjust the width of the arrow */\n"
"    border-left-width: 0px; /* No border on the left side of the arrow */\n"
"    border-top-right-radius: 5px; /* Rounded top-right corner for arrow background */\n"
"    border-bottom-right-radius: 5px; /* Rounded bottom-right corner for arrow background */\n"
"    background-color: #444444; /* Dark Gray for the arrow background */\n"
"}\n"
"\n"
"/* ComboBox Items */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    selection-background-color: #444444; /* Dark Gray on item selection */\n"
"}\n"
"\n"
"/* ComboBox Hovered State */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #444444; /* Dark Gray on item hover */\n"
"}\n"
"\n"
"/* ComboBox Focus State */\n"
"QComboBox:focus {\n"
"    border-color: #77A1D3; /* Light Blue border when focused */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* Tab Widget Stylesheet */\n"
"QTabWidget {\n"
"    background-color: #282828; /* Dark Gray background */\n"
"    color: #FFFFFF; /* White text */\n"
"}\n"
"\n"
"/* Tab Bar Stylesheet */\n"
"QTabBar {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    border-bottom: 2px solid #444444; /* Dark Gray border bottom */\n"
"}\n"
"\n"
"/* Tab Stylesheet */\n"
"QTabWidget::tab-bar {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    border-bottom: 2px solid #444444; /* Dark Gray border bottom */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #1F1F1F; /* Slightly Darker Gray */\n"
"    color: #FFFFFF; /* White text */\n"
"    border-top-left-radius: 4px; /* Rounded top-left corner for tabs */\n"
"    border-top-right-radius: 4px; /* Rounded top-right corner for tabs */\n"
"    padding: 8px 16px; /* Padding for tabs */\n"
"}\n"
"\n"
"/* Tab Hover Stylesheet */\n"
"QTabBar::tab:hover {\n"
"    background-color: #444444; /* Dark Gray on tab hover */\n"
"}\n"
"\n"
"/* Tab Selected Stylesheet */\n"
"QTabBar::tab:selected {\n"
"    background-color: #282828; /* Dark Gray for selected tab */\n"
"    border-bottom: 2px solid #FFFFFF; /* White border bottom for selected tab */\n"
"}\n"
"\n"
"")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem1, 6, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 13, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(200, 16777215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        self.annotationButton = QtWidgets.QCheckBox(self.widget)
        self.annotationButton.setMaximumSize(QtCore.QSize(16777215, 500))
        self.annotationButton.setObjectName("annotationButton")
        self.gridLayout_5.addWidget(self.annotationButton, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 5, 0, 1, 1)
        self.contrast_slider = QtWidgets.QSlider(self.widget)
        self.contrast_slider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setObjectName("contrast_slider")
        self.gridLayout_5.addWidget(self.contrast_slider, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem6, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 11, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem7, 8, 0, 1, 1)
        self.upload_btn = QtWidgets.QPushButton(self.widget)
        self.upload_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.upload_btn.setObjectName("upload_btn")
        self.gridLayout_5.addWidget(self.upload_btn, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(200, 16777215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 14, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_5.addItem(spacerItem9, 12, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.image_layout = GraphicsLayoutWidget(self.widget)
        self.image_layout.setMinimumSize(QtCore.QSize(1000, 500))
        self.image_layout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.image_layout.setObjectName("image_layout")
        self.gridLayout_4.addWidget(self.image_layout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.measurement_label = QtWidgets.QLabel(self.widget)
        self.measurement_label.setMinimumSize(QtCore.QSize(600, 0))
        self.measurement_label.setMaximumSize(QtCore.QSize(16777215, 500))
        self.measurement_label.setText("")
        self.measurement_label.setObjectName("measurement_label")
        self.gridLayout_2.addWidget(self.measurement_label, 0, 0, 1, 1)
        self.measurement_label_2 = QtWidgets.QLabel(self.widget)
        self.measurement_label_2.setMaximumSize(QtCore.QSize(16777215, 500))
        self.measurement_label_2.setText("")
        self.measurement_label_2.setObjectName("measurement_label_2")
        self.gridLayout_2.addWidget(self.measurement_label_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.clear_button = QtWidgets.QPushButton(self.widget)
        self.clear_button.setMaximumSize(QtCore.QSize(500, 500))
        self.clear_button.setObjectName("clear_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clear_button)
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setMaximumSize(QtCore.QSize(500, 500))
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.save_button)
        self.saveimg = QtWidgets.QPushButton(self.widget)
        self.saveimg.setObjectName("saveimg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.saveimg)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_7.addItem(spacerItem11, 0, 0, 1, 1)
        Main.addTab(self.widget, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sagittal_plane = GraphicsLayoutWidget(self.widget1)
        self.sagittal_plane.setMinimumSize(QtCore.QSize(250, 300))
        self.sagittal_plane.setMaximumSize(QtCore.QSize(16777215, 500))
        self.sagittal_plane.setObjectName("sagittal_plane")
        self.gridLayout_8.addWidget(self.sagittal_plane, 0, 0, 1, 1)
        self.axial_plane = GraphicsLayoutWidget(self.widget1)
        self.axial_plane.setMinimumSize(QtCore.QSize(250, 300))
        self.axial_plane.setMaximumSize(QtCore.QSize(16777215, 500))
        self.axial_plane.setObjectName("axial_plane")
        self.gridLayout_8.addWidget(self.axial_plane, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.coronal_plane = GraphicsLayoutWidget(self.widget1)
        self.coronal_plane.setMinimumSize(QtCore.QSize(250, 300))
        self.coronal_plane.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.coronal_plane.setObjectName("coronal_plane")
        self.gridLayout_9.addWidget(self.coronal_plane, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        Main.addTab(self.widget1, "")
        self.volume_rendering = QtWidgets.QWidget()
        self.volume_rendering.setObjectName("volume_rendering")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.volume_rendering)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.iso_label = QtWidgets.QLabel(self.volume_rendering)
        self.iso_label.setMinimumSize(QtCore.QSize(20, 0))
        self.iso_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.iso_label.setObjectName("iso_label")
        self.gridLayout_13.addWidget(self.iso_label, 0, 0, 1, 1)
        self.iso_slider = QtWidgets.QSlider(self.volume_rendering)
        self.iso_slider.setMinimumSize(QtCore.QSize(500, 0))
        self.iso_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.iso_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iso_slider.setObjectName("iso_slider")
        self.gridLayout_13.addWidget(self.iso_slider, 0, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.volume_rendering)
        self.lcdNumber.setMinimumSize(QtCore.QSize(20, 20))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_13.addWidget(self.lcdNumber, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem12, 0, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_13, 0, 1, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.VR_comboBox = QtWidgets.QComboBox(self.volume_rendering)
        self.VR_comboBox.setMinimumSize(QtCore.QSize(110, 0))
        self.VR_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.VR_comboBox.setObjectName("VR_comboBox")
        self.VR_comboBox.addItem("")
        self.VR_comboBox.addItem("")
        self.VR_comboBox.addItem("")
        self.gridLayout_14.addWidget(self.VR_comboBox, 0, 1, 1, 1)
        self.load = QtWidgets.QPushButton(self.volume_rendering)
        self.load.setMinimumSize(QtCore.QSize(52, 0))
        self.load.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.load.setObjectName("load")
        self.gridLayout_14.addWidget(self.load, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.volume_rendering)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.VR_widget = QtWidgets.QWidget(self.groupBox)
        self.VR_widget.setObjectName("VR_widget")
        self.gridLayout_15.addWidget(self.VR_widget, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        Main.addTab(self.volume_rendering, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.coronal_plane_3 = GraphicsLayoutWidget(self.tab)
        self.coronal_plane_3.setGeometry(QtCore.QRect(200, 20, 441, 541))
        self.coronal_plane_3.setMinimumSize(QtCore.QSize(250, 300))
        self.coronal_plane_3.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.coronal_plane_3.setObjectName("coronal_plane_3")
        self.coronal_plane_2 = GraphicsLayoutWidget(self.tab)
        self.coronal_plane_2.setGeometry(QtCore.QRect(660, 20, 431, 541))
        self.coronal_plane_2.setMinimumSize(QtCore.QSize(250, 300))
        self.coronal_plane_2.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.coronal_plane_2.setObjectName("coronal_plane_2")
        Main.addTab(self.tab, "")

        self.retranslateUi(Main)
        Main.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "TabWidget"))
        self.comboBox.setItemText(0, _translate("Main", "line"))
        self.comboBox.setItemText(1, _translate("Main", "freehand"))
        self.comboBox.setItemText(2, _translate("Main", "circle"))
        self.annotationButton.setText(_translate("Main", "Add Annotations"))
        self.label.setText(_translate("Main", "Contrast Adjustment"))
        self.label_2.setText(_translate("Main", "Annotation tools"))
        self.upload_btn.setText(_translate("Main", "Upload DICOM"))
        self.clear_button.setText(_translate("Main", "Clear"))
        self.save_button.setText(_translate("Main", "Save"))
        self.saveimg.setText(_translate("Main", "Save img"))
        Main.setTabText(Main.indexOf(self.widget), _translate("Main", "Viewer"))
        Main.setTabText(Main.indexOf(self.widget1), _translate("Main", "MPR"))
        self.iso_label.setText(_translate("Main", "ISO Value"))
        self.VR_comboBox.setItemText(0, _translate("Main", "Choose Rendering Technique "))
        self.VR_comboBox.setItemText(1, _translate("Main", "Surface Rendering "))
        self.VR_comboBox.setItemText(2, _translate("Main", "Ray Casting Rendering\n"
""))
        self.load.setText(_translate("Main", "Load File"))
        Main.setTabText(Main.indexOf(self.volume_rendering), _translate("Main", "3D Volume Rendering"))
        Main.setTabText(Main.indexOf(self.tab), _translate("Main", "Page"))
from pyqtgraph import GraphicsLayoutWidget
